# Création des 4 environnements de déploiement via le principe de Namespace.
# À appliquer une seule fois sur le cluster :  kubectl apply -f k8s/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    environment: qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
